import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
//import { Inter } from "next/font/google";
import styles from "@/styles/Rate.module.css";

import Card from "../../component/card/Card";

import MySVG from "../../public/illustration-thank-you.svg";

export default function Rate(props) {
  const router = useRouter();
  const { rate } = router.query;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card>
        <div className={styles.Img}>
          <Image src={MySVG} alt="slip" />
        </div>
        <div className={styles.Rate}>
          {rate != 0 ? `You selected ${rate} out of 5` : `No rate selected`}
        </div>
        <h3 className={styles.Header}>Thank you!</h3>
        <p className={styles.Text}>
          We appreciate you taking the time to give a rating. If you ever need
          more support, don’t hesitate to get in touch!
        </p>
      </Card>
    </>
  );
}
